gui:
  language: 'en'
  timeFormat: 02.01.2006
  shortTimeFormat: 15:04
  nerdFontsVersion: '3'
  showFileTree: true
  showListFooter: false
  showCommandLog: false
  showRandomTip: false
  commitHashLength: 3
  showDivergenceFromBaseBranch: arrowAndNumber # or 'onlyArrow'
  expandFocusedSidePanel: true
  expandedSidePanelWeight: 3
  commitAuthorShortLength: 4
os:
  edit: 'nvim {{filename}}'
  editAtLine: 'nvim +{{line}} -- {{filename}}'
git:
  diffContextSize: 2
