gui:
  language: 'en'
  timeFormat: '2006/01/02 15:04'
  showIcons: true
  showFileTree: true
  showListFooter: false
  showCommandLog: false
  showRandomTip: false
  commitHashLength: 3
os:
  edit: 'nvim {{filename}}'
  editAtLine: 'nvim +{{line}} -- {{filename}}'
git:
  diffContextSize: 2
keybinding:
  universal:
    nextTab: '%'
