dofile(vim.g.base46_cache .. "defaults")
dofile(vim.g.base46_cache .. "statusline")
dofile(vim.g.base46_cache .. "syntax")
dofile(vim.g.base46_cache .. "treesitter")
dofile(vim.g.base46_cache .. "tbline")
dofile(vim.g.base46_cache .. "devicons")
dofile(vim.g.base46_cache .. "telescope")
